#jdbc:mysql://[mysql-docker-container-name]:[mysql-port]/[db-name]
#jdbc:mysql://mysqldb:3306/auth_database?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
#jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
server:
  error:
    include-message: always
    include-binding-errors: always
jwt:
  secret: adads23@3r@#$ADQ1
  expirationTime: 360000
---
springdoc:
  swagger-ui:
    path: /swagger-ui.html
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_database?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: app_user #${DATABASE_USER}
    password: root #${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

---

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by email
  search: Returns specific user by email
  me: Returns current user's data