#jdbc:mysql://[mysql-docker-container-name]:[mysql-port]/[db-name]
#jdbc:mysql://mysqldb:3306/auth_database?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

